class Config:

    def __init__(
        self,
        OPEN_LUCKY_BLOCKS=True,
        OPEN_PARTY_BOXES=True,
        OPEN_LARGE_GIFT_BAGS=True,
        OPEN_SMALL_GIFT_BAGS=True,
        OPEN_PINATAS=True,
        CREATE_SECRET_KEYS=True,
        CREATE_CRYSTAL_KEYS=True,
        OPEN_FREE_GIFTS=True,
        OPEN_RANK_REWARDS=True,
        MAX_ORANGE_BOOSTS=True,
        MAX_BANANA_BOOSTS=True,
        MAX_APPLE_BOOSTS=True,
        MAX_PINEAPPLE_BOOSTS=True,
        MAX_RAINBOW_FRUITS_BOOSTS=True,
        SAVE_LOGS=False,
        GATHER_ITEMS=True,
    ):
        self.OPEN_LUCKY_BLOCKS = OPEN_LUCKY_BLOCKS
        self.OPEN_PARTY_BOXES = OPEN_PARTY_BOXES
        self.OPEN_LARGE_GIFT_BAGS = OPEN_LARGE_GIFT_BAGS
        self.OPEN_SMALL_GIFT_BAGS = OPEN_SMALL_GIFT_BAGS
        self.OPEN_PINATAS = OPEN_PINATAS
        self.CREATE_SECRET_KEYS = CREATE_SECRET_KEYS
        self.CREATE_CRYSTAL_KEYS = CREATE_CRYSTAL_KEYS
        self.OPEN_FREE_GIFTS = OPEN_FREE_GIFTS
        self.OPEN_RANK_REWARDS = OPEN_RANK_REWARDS
        self.MAX_ORANGE_BOOSTS = MAX_ORANGE_BOOSTS
        self.MAX_APPLE_BOOSTS = MAX_APPLE_BOOSTS
        self.MAX_BANANA_BOOSTS = MAX_BANANA_BOOSTS
        self.MAX_PINEAPPLE_BOOSTS = MAX_PINEAPPLE_BOOSTS
        self.MAX_RAINBOW_FRUITS_BOOSTS = MAX_RAINBOW_FRUITS_BOOSTS
        self.SAVE_LOGS = SAVE_LOGS
        self.GATHER_ITEMS = GATHER_ITEMS
