# Non Script
LOGS_FOLDER = "logs"
HEADER_FONT = ("Arial Bold", 12)

# Strings
START_SCRIPT = "Start Script"
SELECT_ALL = "Select All"
SELECT_NONE = "Select None"
OPEN_LUCKY_BLOCKS = "OPEN_LUCKY_BLOCKS"
OPEN_PARTY_BOXES = "OPEN_PARTY_BOXES"
OPEN_LARGE_GIFT_BAGS = "OPEN_LARGE_GIFT_BAGS"
OPEN_SMALL_GIFT_BAGS = "OPEN_SMALL_GIFT_BAGS"
OPEN_PINATAS = "OPEN_PINATAS"
CREATE_SECRET_KEYS = "CREATE_SECRET_KEYS"
CREATE_CRYSTAL_KEYS = "CREATE_CRYSTAL_KEYS"
OPEN_FREE_GIFTS = "OPEN_FREE_GIFTS"
OPEN_RANK_REWARDS = "OPEN_RANK_REWARDS"
STATUS = "STATUS"
LUCKY_BLOCK = "Lucky Block"
PINATA = "Pinata"
LARGE_GIFT_BAG = "Large Gift Bag"
SMALL_GIFT_BAG = "Small Gift Bag"
PARTY_BOX = "Party Box"
SECRET_KEY = "Secret Key"
CRYSTAL_KEY = "Crystal Key"

# Screenshot Images
MENU_IMG = "images/menu.png"
ITEMS_IMG = "images/items.png"
PARTY_BOX_IMG = "images/party_box.png"
OK_IMG = "images/ok.png"
LUCKY_BLOCK_IMG = "images/lucky_block.png"
LARGE_GIFT_BAG_IMG = "images/large_gift_bag.png"
SMALL_GIFT_BAG_IMG = "images/small_gift_bag.png"
PINATA_IMG = "images/pinata.png"
SECRET_KEY_LOWER_IMG = "images/secret_key_lower.png"
SECRET_KEY_UPPER_IMG = "images/secret_key_upper.png"
YES_IMG = "images/yes.png"
CRYSTAL_KEY_LOWER_IMG = "images/crystal_key_lower.png"
CRYSTAL_KEY_UPPER_IMG = "images/crystal_key_upper.png"
FREE_GIFT_READY_IMG = "images/free_gift_ready.png"
FREE_GIFTS_POPUP_IMG = "images/free_gifts_popup.png"
REDEEM_GIFT_1_IMG = "images/redeem_gift_1.png"
REDEEM_GIFT_2_IMG = "images/redeem_gift_2.png"
REDEEM_GIFT_3_IMG = "images/redeem_gift_3.png"
REDEEM_GIFT_4_IMG = "images/redeem_gift_4.png"
RANK_REWARDS_CLAIMABLE_IMG = "images/rank_rewards_claimable.png"
CLAIM_RANK_REWARD_IMG = "images/claim_rank_reward.png"
RANK_REWARDS_SCROLL_IMG = "images/rank_rewards_scroll.png"
