# Strings
OPEN_LUCKY_BLOCKS = "OPEN_LUCKY_BLOCKS"
OPEN_PARTY_BOXES = "OPEN_PARTY_BOXES"
OPEN_LARGE_GIFT_BAGS = "OPEN_LARGE_GIFT_BAGS"
OPEN_SMALL_GIFT_BAGS = "OPEN_SMALL_GIFT_BAGS"
OPEN_PINATAS = "OPEN_PINATAS"
CREATE_SECRET_KEYS = "CREATE_SECRET_KEYS"
CREATE_CRYSTAL_KEYS = "CREATE_CRYSTAL_KEYS"
STATUS = "STATUS"
LUCKY_BLOCK = "Lucky Block"
PINATA = "Pinata"
LARGE_GIFT_BAG = "Large Gift Bag"
SMALL_GIFT_BAG = "Small Gift Bag"
PARTY_BOX = "Party Box"
SECRET_KEY = "Secret Key"
CRYSTAL_KEY = "Crystal Key"

# Screenshot Images
MENU_IMG = "images/menu.png"
ITEMS_IMG = "images/items.png"
PARTY_BOX_IMG = "images/party_box.png"
OK_IMG = "images/ok.png"
LUCKY_BLOCK_IMG = "images/lucky_block.png"
LARGE_GIFT_BAG_IMG = "images/large_gift_bag.png"
SMALL_GIFT_BAG_IMG = "images/small_gift_bag.png"
PINATA_IMG = "images/pinata.png"
SECRET_KEY_LOWER_IMG = "images/secret_key_lower.png"
SECRET_KEY_UPPER_IMG = "images/secret_key_upper.png"
YES_IMG = "images/yes.png"
CRYSTAL_KEY_LOWER_IMG = "images/crystal_key_lower.png"
CRYSTAL_KEY_UPPER_IMG = "images/crystal_key_upper.png"
